### ISSUE TITLE
Exclusion feature

### ISSUE THREAD

**Issue by ajagnanan** [Tim-B/grunt-aws-lambda#29]
Hello,

Can you add the ability to exclude files in the lambda_package task? Or modify the include_files property to add only those files specified and not include the entire project folder? thanks.

**Comment by Tim-B** [comment]
I think if you add the files you want to exclude to your `.npmignore` file it'll have this effect.

**Comment by ajagnanan** [comment]
Yup, but I was trying to manage several functions in one project. The .npmignore would be a global exclusion, so wouldn't be ideal.

**Comment by Tim-B** [comment]
I was thinking about how best to support that use case (ie. a large number of similar or related functions), and I'd suggest one of the following approaches:

1. Implement a router, which calls a different function depending on a parameter passed with the event. [Here's an example](https://github.com/Tim-B/codepipeline-opsworks-deployer/blob/master/index.js#L23) in one of my other projects.

2. Keep them separate in separate directories. This makes sense in just about any case where all functions don't have the same dependencies seeing as otherwise all the functions would share the same package.json 

3. Make separate deploy and package functions for each task setting the `package_folder` option and possibly also the `include_files` if you need to include some shared files. There's an example of defining multiple tasks [here(https://github.com/Tim-B/codepipeline-opsworks-deployer/blob/master/Gruntfile.js#L5)] (in that case for the invoke task).
