### ISSUE TITLE
Need check for archive size before upload

### ISSUE THREAD

**Issue by zoellner** [Tim-B/grunt-aws-lambda#49]
When the zip archive ends up being > 50MB the upload fails with the following (misleading) error message:

Warning: Package upload failed, check you have lambda:UpdateFunctionCode permissions. Use --force to continue.

There should be a check for the archive size before trying to upload.

**Comment by Tim-B** [comment]
Probably not a bad idea. Out of interest, do you expect your package to be that big? Some users have forgotten to add their dist folder to `.npmignore` causing their packages to be excessively big.

**Comment by zoellner** [comment]
I'm around 20MB for most cases, but since I can't exclude any npm dependencies from the archive (related to discussion in #31), I have one project where the files is just above the limit.

**Comment by Tim-B** [comment]
I've updated the error message to indicate the issue could be due to the package being too big.

Regarding your use case, instead of having all your packages share a package.json could you perhaps have one Lambda function and one package.json per directory within your project, then have multiple invoke/package/deploy configurations in your parent `Gruntfile` each with different directory settings such as `package_folder`?

I haven't tried it, but if that works I think it might be more manageable.

**Comment by zoellner** [comment]
that's essentially what I ended up doing. But I think an updated error message is helpful

**Comment by Tim-B** [comment]
Thanks, glad to hear that approach worked for you. I'll close this issue for now.
